apiVersion: apps/v1 #api版本
kind: Deployment
metadata:
  labels: #资源标签
    app: cloud-native
  name: cloud-native #资源名
  namespace: nju17 #资源部署的名空间
spec:
  replicas: 3 #副本数目
  strategy:
    type: RollingUpdate #滚动更新策略
    rollingUpdate:
      maxSurge: 25% #最大额外副本
      maxUnavailable: 25% #更新中进入不可用状态Pod的最大值
  selector:
    matchLabels:
      app: cloud-native #匹配标签
  template:
    metadata:
      annotations: #自定义注解，接入Prometheus
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud-native #资源标签
    spec:
      containers:
        - image: harbor.edu.cn/nju17/cloud-native:{VERSION} #镜像地址
          name: cloud-native #容器名
---
apiVersion: v1 #api版本
kind: Service
metadata:
  name: cloud-native #资源名
  labels:
    app: cloud-native #资源标签
spec:
  type: NodePort
  selector:
    app: cloud-native
  ports:
    - name: tcp8080 #端口名
      protocol: TCP #TCP协议
      port: 8080 #service端口
      targetPort: 8080 #容器暴露的端口