apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-native #需要名字
  name: cloud-native
  namespace: nju17
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: cloud-native #需要名字
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud-native #需要名字
    spec:
      containers:
        - image: harbor.edu.cn/nju17/cloud-native:9
          name: cloud-native #需要名字
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native #需要名字
  labels:
    app: cloud-native #需要名字
spec:
  type: NodePort
  selector:
    app: cloud-native #需要名字
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080