apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: serverName #需要名字
  name: serverName #需要名字
  namespace: nju17
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: serverName #需要名字
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: serverName #需要名字
    spec:
      containers:
        - image: harbor.edu.cn/nju17/serverName:{VERSION}
          name: serverName #需要名字
---
apiVersion: v1
kind: Service
metadata:
  name: serverName #需要名字
  labels:
    app: serverName #需要名字
spec:
  type: NodePort
  selector:
    app: serverName #需要名字
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080